name: formgen_generator
description: formgen generator
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  build: ^1.1.3
  source_gen: ^0.9.4+2

  formgen_lib:
    path: ../formgen_lib

  code_builder: ^3.2.0
  dart_style: any

dev_dependencies:
  test: ^1.6.2

